<?php

/**
 * This is the model base class for the table "autor".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Autor".
 *
 * Columns in table "autor" available as properties of the model,
 * followed by relations of table "autor" available as properties of the model.
 *
 * @property integer $id
 * @property string $nome
 * @property string $linkExterno
 * @property string $sobre
 *
 * @property Post[] $posts
 */
abstract class BaseAutor extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'autor';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Autor|Autors', $n);
	}

	public static function representingColumn() {
		return 'nome';
	}

	public function rules() {
		return array(
			array('nome', 'required'),
			array('nome', 'length', 'max'=>100),
			array('linkExterno, sobre', 'length', 'max'=>255),
			array('linkExterno, sobre', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nome, linkExterno, sobre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'posts' => array(self::HAS_MANY, 'Post', 'idUsuario'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nome' => Yii::t('app', 'Nome'),
			'linkExterno' => Yii::t('app', 'Link Externo'),
			'sobre' => Yii::t('app', 'Sobre'),
			'posts' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('linkExterno', $this->linkExterno, true);
		$criteria->compare('sobre', $this->sobre, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}